### ISSUE TITLE
Failing on a method-local classes example

### ISSUE THREAD

**Issue by br4ch1st0chr0n3** [polystat/j2eo#109]
Hi! I'm trying to run j2eo on the following code

```java
package tryMethod;

class Try {
    public boolean myC() {
        class c {
            public int value = 11;
            public int getValue(){
                return this.value;
            }
        }
        class d extends c {} 
        d o = new d();
        return (o.getValue() == 11);
    }
 
    public static void main(String[] args){
        var t = new Try();
        System.out.println(t.myC());
    }
}
```
Expected something similar to [this](https://br4ch1st0chr0n3.github.io/eo-editor/?snippet=%5B%5D%20%3E%20myC%0A%20%20%5B%5D%20%3E%20c%0A%20%20%20%20class%20%3E%20%40%0A%20%20%20%2011%20%3E%20value%0A%20%20%20%20%5Bself%5D%20%3E%20getValue%0A%20%20%20%20%20%20seq%20%3E%20%40%0A%20%20%20%20%20%20%20%20self.value%0A%20%20seq%20%3E%20%40%0A%20%20%20%20%5B%5D%20%3E%20d%0A%20%20%20%20%20%20c%20%3E%20%40%0A%20%20%20%20d%20%3E%20o%0A%20%20%20%20o.getValue.eq%2011%0A), but get
```sh
[main] INFO  - Parsing files in directory "/home/user/Desktop/j2eo-master/src/main/java/tryMethod/Try.java"
[main] INFO  - Progress: 0.00% / 100.0%. --- Files left: 1; file: src/main/java/tryMethod/Try.java
Exception in thread "main" java.lang.NullPointerException: clsDec.name must not be null
        at util.NewGeneratorKt.generateThis(NewGenerator.kt:88)
        at util.NewGeneratorKt.generateNew(NewGenerator.kt:115)
        at translator.ClassesKt.mapClass(Classes.kt:53)
        at translator.DeclarationsKt.mapDeclaration(Declarations.kt:46)
        at translator.BlocksKt.mapBlockStatement(Blocks.kt:78)
        at translator.BlocksKt.mapBlock(Blocks.kt:33)
        at translator.BlocksKt.mapBlock$default(Blocks.kt:15)
        at translator.MethodsKt.mapMethodDeclaration(Methods.kt:59)
        at translator.DeclarationsKt.mapClassDeclaration(Declarations.kt:24)
        at util.NewGeneratorKt.generateThis(NewGenerator.kt:100)
        at util.NewGeneratorKt.generateNew(NewGenerator.kt:115)
        at translator.ClassesKt.mapClass(Classes.kt:53)
        at translator.Translator.mapTopLevelComponent(Translator.kt:85)
        at translator.Translator.mapSimpleCompilationUnit(Translator.kt:49)
        at translator.Translator.translate(Translator.kt:22)
        at main.Main2.main(Main2.kt:106)
```

Unimportant: this is a hopefully correct translation of Python code

```python
def myC():
    class c:
        value = 11
        def getValue(self): return self.value
    class d(c): pass
    o = d()
    return o.getValue() == 11
```

**Comment by someilay** [comment]
FIXED
