### ISSUE TITLE
Support floating decimals

### ISSUE THREAD

**Issue by fizruk** [polystat/j2eo#116]
I have tried to use J2EO on [elastic/elasticsearch](https://github.com/elastic/elasticsearch) repository, and it broke file [JdbcPreparedStatementTests.java](https://github.com/elastic/elasticsearch/blob/46943982c9ef92752a09e4bf0f5f9419e1c187f8/x-pack/plugin/sql/jdbc/src/test/java/org/elasticsearch/xpack/sql/jdbc/JdbcPreparedStatementTests.java#L345), on this line:

```java
        Float floatNotInt = 5_155_000_000f;
```

Here's the error message:

```
[845/15611] Translating /Users/nikolaikudasov/git/misc/elasticsearch/x-pack/plugin/sql/jdbc/src/test/java/org/elasticsearch/xpack/sql/jdbc/JdbcPreparedStatementTests.java
Exception in thread "main" java.lang.NumberFormatException: For input string: "5_155_000_000f"
	at java.base/jdk.internal.math.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:2054)
	at java.base/jdk.internal.math.FloatingDecimal.parseFloat(FloatingDecimal.java:122)
	at java.base/java.lang.Float.parseFloat(Float.java:476)
	at translator.LiteralsKt.mapLiteral(Literals.kt:20)
	at translator.ExpressionsKt.mapExpression(Expressions.kt:24)
	at translator.InitializersKt.mapInitializerSimple(Initializers.kt:20)
	at translator.InitializersKt.mapInitializer(Initializers.kt:12)
	at translator.MethodsKt.parseExprTask(Methods.kt:132)
	at translator.MethodsKt.parseExprTasks(Methods.kt:118)
	at translator.MethodsKt.mapMethodDeclaration(Methods.kt:75)
	at translator.DeclarationsKt.mapClassDeclaration(Declarations.kt:28)
	at util.NewGeneratorKt.generateThis(NewGenerator.kt:43)
	at util.NewGeneratorKt.generateNew(NewGenerator.kt:58)
	at translator.ClassesKt.mapClass(Classes.kt:51)
	at translator.Translator.mapTopLevelComponent(Translator.kt:87)
	at translator.Translator.mapSimpleCompilationUnit(Translator.kt:51)
	at translator.Translator.translate(Translator.kt:24)
	at main.Main2.main(Main2.kt:94)
```

**Comment by someilay** [comment]
FIX: https://github.com/polystat/j2eo/pull/122

**Comment by yegor256** [comment]
Fixed by #122, merged in 2022
